AWSTemplateFormatVersion: '2010-09-09'
Description: Jenkins on Amazon EKS

Resources:
  MyEksCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: MyEksCluster
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-12345
          - subnet-67890
      RoleArn: arn:aws:iam::123456789012:role/EKSRole

  MyNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref MyEksCluster
      NodeRole: arn:aws:iam::123456789012:role/EKSNodeRole
      Subnets:
        - subnet-12345
        - subnet-67890
      ScalingConfig:
        DesiredSize: 2
        MinSize: 1
        MaxSize: 3
      InstanceTypes:
        - t3.medium

  JenkinsFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose